---
- name: install nginx server
  hosts: linux0
  become: yes

  tasks:
  - name: Update  apt packages
    apt:
      update_cache: yes
      cache_valid_time: 86400 #One day

  - name: install nginx server
    apt: name=nginx state=present
